name: 🐞 Bug report
description: Report broken functionality.
labels: [bug]

body:
- type: markdown
  attributes:
    value: |
      🧐 **Guidelines:**

      - Search through [existing issues](https://github.com/ueman/feedback/issues?q=is%3Aissue) first to ensure that this bug has not been reported before.
      - Write a descriptive title for your issue. Avoid generic or vague titles such as "Something's not working" or "A couple of problems".
      - Keep your issue focused on one single problem. If you have multiple bug reports, please create separate issues for each of them.
      - Provide as much context as possible in the details section. Include screenshots, screen recordings, links, references, or anything else you may consider relevant.
      - If you want to ask a question instead of reporting a bug, please use [discussions](https://github.com/ueman/feedback/discussions/new) instead.

- type: input
  attributes:
    label: Version
    description: Which version of feedback does this bug affect?
    placeholder: ver X.Y.Z
  validations:
    required: true

- type: dropdown
  attributes:
    label: Library
    description: Which library is affected by this bug?
    multiple: true
    options:
    - feedback
    - feedback_gitlab
    - feedback_sentry
  validations:
    required: true

- type: dropdown
  attributes:
    label: Flutter channel
    description: Which Flutter channel are you using?
    multiple: true
    options:
    - stable
    - beta
    - dev
    - master
  validations:
    required: true

- type: input
  attributes:
    label: Flutter version
    description: Which Flutter version are you using?
  validations:
    required: true

- type: dropdown
  attributes:
    label: Platform
    description: Which platform are you using?
    multiple: true
    options:
    - Android
    - iOS
    - Web
    - Linux
    - macOS
    - Windows
  validations:
    required: true

- type: textarea
  attributes:
    label: Details
    description: Clear and thorough explanation of the bug.
    placeholder: I was doing X expecting Y to happen, but Z happened instead.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Minimum steps required to reproduce the bug.
    placeholder: |
      - Step 1
      - Step 2
      - Step 3
  validations:
    required: true

- type: textarea
  attributes:
    label: Output of `flutter doctor -v`
    description: The input is automatically formatted as shell output
    render: shell